### ISSUE TITLE
FDroid containing pre-release version

### ISSUE THREAD

**Issue by TwizzyDizzy** [maks/MGit#171]
Hi folks,

I just stumbled across this issue: I installed MGit from FDroid and what I got was a crashing (pre-release) version 1.5.2. I don't know if that's what is intended or whether the author of MGit has control over this, but I wanted bring this to your attention.

The 1.5.1 APK (latest stable) is working as expected.

Cheers
Thomas

**Comment by maks** [comment]
Thank you for reporting this.
I unfortunately don't have any control over the versions published in F-Droid **BUT** in this case, 1.5.2 is the latest release.
Could you please add a comment here with more information regarding what you were doing in the app that caused the crash, the device you are using (and which Android version its running) and if possible also include the debug information (stacktrace) that gets displayed when the app crashes.

**Comment by TwizzyDizzy** [comment]
Hi @maks,

so fdroid seems to always fetch the latest release, independent of what this release is tagged as? That's rather odd.

![image](https://user-images.githubusercontent.com/179595/27374609-ba1162bc-566c-11e7-99d6-3ebc44122224.png)

Unfortunately I cannot provide you with any stacktrace as the app just crashed (and whatever mechanism you have in place to catch the trace did not fire). Android just said that it crashed.

My device: Redmi Note 3 (Codename kate - the 3GB version of kenzo)
My OS: LineageOS 14.1-20170614-NIGHTLY-kenzo
Underlying Android Version: 7.1.2

Cheers
Thomas

**Comment by maks** [comment]
Ah, I see now. Sorry about that, I forgot to go back and mark it as the latest release as initially it was marked pre-release when it went out into the Google Play Beta channel.
I've now fixed that up.
But you are correct, F-Droid just looks at the git tag naming and not the pre-release flag which is a Github proprietary feature and not part of standard git.
Thank you for adding the extra information. Luckily I have access to the Redmi Note 4 at the moment running Lineage 14.1 custom build so I can test on it and see if I can reproduce the issue you are seeing.

**Comment by polyzen** [comment]
The solution to this would be to add `-beta` in these cases. http://semver.org/

**Comment by maks** [comment]
@polyzen Yes thanks, I think I might do that from now on instead of using Github's pre-release marker.

@TwizzyDizzy I'm afraid I can't replicate your issue using the current apk from F-Droid and my test device which is almost identical to yours. Is this a new install or you upgraded from a previous version of MGit?

**Comment by TwizzyDizzy** [comment]
@maks fair enough. Thanks for trying to replicate. In my case this happened on a totally vanilla install of MGit on the aforementioned version of LineageOS.

I think I'll give it another shot later... and then get back to you.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Hi again,

I tried again with (new now officially released) 1.5.2 from FDroid - still the same. 1.5.1 worked on the very same phone, 1.5.2 crashes instantly after touching the app icon (first image), on relaunching it leads to the second image.

![first](https://user-images.githubusercontent.com/179595/27560007-e7a8302a-5ac2-11e7-8e6f-bfc97a63e6e1.png)

![second](https://user-images.githubusercontent.com/179595/27560008-e7a8cc2e-5ac2-11e7-82ae-c29c480e6fec.png)

If you can't replicate the behaviour, I'm at a loss here, currently. No idea where to start. Maybe ADB debugging an the handing you logs?

Cheers
Thomas

**Comment by maks** [comment]
That is very strange, 1.5.2 has a new feature in it to display useful information when the app crashes, to allow users like yourself to then send it on to me to help in debugging crashes, so not sure why you are not seeing that come up. I'll investigate some more as it might be that very feature causing an issue on your device.

**Comment by TwizzyDizzy** [comment]
Issue is now gone with the 1.5.3 release.

Cheers,
Thomas
